/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex2;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class MainFrame extends javax.swing.JFrame {

    Socket socket;
    DataInputStream input;
    DataOutputStream output;
    boolean fezLikeDislike = false;
    boolean mostraCitacao = false;
    boolean fezCancel = true;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public void mostraDialog(String texto) {
        JOptionPane.showMessageDialog(this, texto);

    }

    public void verificaComando(String comando) {

        try {

            switch (comando) {

                case "like":
                    if (fezLikeDislike == false) {
                        System.out.println("faz like");
                        citacaoTA.setText("");
                        output.writeUTF("like");
                        mostraResposta();
                        mostraDialog("Like bem sucedido!");
                        fezLikeDislike = true;
                        fezCancel = false;
                    } else {
                        mostraDialog("Já fez like ou dislike, insira cancel para poder fazer novamente!");
                    }
                    break;
                case "dislike":
                    if (fezLikeDislike == false) {
                        System.out.println("dislike");
                        citacaoTA.setText("");
                        output.writeUTF("dislike");
                        mostraResposta();
                        mostraDialog("Dislike bem sucedido!");
                        fezLikeDislike = true;
                        fezCancel = false;
                    } else {
                        mostraDialog("Já fez like ou dislike, insira cancel para poder fazer novamente!");
                    }
                    break;
                case "cancel":
                    if (fezCancel == false) {
                        fezLikeDislike = false;
                        output.writeUTF("cancel");
                        citacaoTA.setText("");
                        mostraResposta();
                        fezLikeDislike = false;
                        fezCancel = true;
                    } else {
                        mostraDialog("Não pode fazer cancel duas vezes ou antes de fazer like/dislike!");
                    }
                    break;
                case "end":
                    output.writeUTF("end");
                    mostraDialog("Cliente saiu da sessão!");
                    citacaoTA.setText("");
                    comandosClienteTF.setText("");
                    socket.close();
                    mostraCitacao = false;
                    break;
                default:
                    mostraDialog("invalid command");
            }
        } catch (IOException ex) {
            System.getLogger(MainFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }

    public void mostraResposta() {
        System.out.println("olaa");
        try {

            String resposta = input.readUTF();
            System.out.println("Resposta: " + resposta);
            citacaoTA.append(resposta + "\n");

            //input.close();
            //socket.close();
        } catch (Exception e) {
            System.out.println("Erro: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        citacaoTA = new javax.swing.JTextArea();
        btnPedeCitacao = new javax.swing.JButton();
        ipTF = new javax.swing.JTextField();
        portoTF = new javax.swing.JTextField();
        comandosClienteTF = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        citacaoTA.setColumns(20);
        citacaoTA.setRows(5);
        jScrollPane1.setViewportView(citacaoTA);

        btnPedeCitacao.setText("Pedir Citação");
        btnPedeCitacao.addActionListener(this::btnPedeCitacaoActionPerformed);

        ipTF.addActionListener(this::ipTFActionPerformed);

        comandosClienteTF.addActionListener(this::comandosClienteTFActionPerformed);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);

        jLabel1.setText("IP:");

        jLabel2.setText("Porto:");

        jLabel3.setText("Comando");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(comandosClienteTF, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(portoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipTF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnEntrar)
                    .addComponent(btnPedeCitacao))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(ipTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedeCitacao)
                    .addComponent(portoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comandosClienteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedeCitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedeCitacaoActionPerformed
        if (socket == null || socket.isClosed()) {
            mostraDialog("Tem que entrar numa sessão primeiro!");
        } else {
            if (mostraCitacao == false) {
                mostraResposta();
                mostraCitacao = true;
            } else {
                mostraDialog("Já pediu uma citação, tem que entrar noutra sessão introduzindo o comando end para sair da atual!");
            }
        }
    }//GEN-LAST:event_btnPedeCitacaoActionPerformed

    private void ipTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipTFActionPerformed

    private void comandosClienteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comandosClienteTFActionPerformed


    }//GEN-LAST:event_comandosClienteTFActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String ip = this.ipTF.getText();
        String porto = this.portoTF.getText();

        boolean verificaPorto = true;

        try {

            Integer.valueOf(porto);
        } catch (NumberFormatException e) {
            verificaPorto = false;
        }

        if (ip.isEmpty() || porto.isEmpty()) {
            mostraDialog("Tem que introduzir o IP e o porto!");
        } else {
            if (verificaPorto == true) {
                if (socket == null || socket.isClosed()) {
                    try {
                        this.socket = new Socket(ip, Integer.parseInt(porto));
                        mostraDialog("Cliente entrou com sucesso na sessão!");
                        this.output = new DataOutputStream(socket.getOutputStream());
                        this.input = new DataInputStream(socket.getInputStream());
                    } catch (Exception e) {
                    }
                } else {
                    mostraDialog("Já está numa sessão, saia com o comando end!");
                }
            } else {
                mostraDialog("O porto tem que ser um número inteiro!");
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String comando = this.comandosClienteTF.getText();
        if (socket == null || socket.isClosed()) {
            mostraDialog("Tem que iniciar sessão primeiro!");
        } else {
            if (comando.isEmpty()) {
                mostraDialog("Tem que inserir um comando!");
            } else {
                verificaComando(comando);
            }
    }//GEN-LAST:event_btnEnviarActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnPedeCitacao;
    private javax.swing.JTextArea citacaoTA;
    private javax.swing.JTextField comandosClienteTF;
    private javax.swing.JTextField ipTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField portoTF;
    // End of variables declaration//GEN-END:variables
}
